### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#752]
This is a running list of proposed improvements and corrections to the documentation. Includes fixes described in other issues, which are tagged appropriately. Since documentation is more/less tangential to producing good science results, these all fall to a lower priority than some of the other git issues. But good documentation also reduces the onboarding time for new users and enables contributions from a wider community. So if anyone has time/interest, please feel free to jump on any of the tasks below, grouped by relative priority. User tags indicate assignment.

High
- [ ] Add a "Changes in this release" page, which is an overview of key recent changes in the changelog, aimed at typical users. 
- [ ] Add stroopwafel interface file to compas, and a quick description to the documentation #741 @FloorBroekgaarden @stellarphysicsandpopulations 
- [ ] Add detailed evolution example using runSubmit #740 @reinhold-willcox @themikelau 
- [x] Add yaml install #750 @avigna 
- [ ] Ensure links to websites, images, and other documentation pages are up to date

Medium
- [ ] Clean up online docs file structure for clarity (c.f [ozstar docs](https://supercomputing.swin.edu.au/docs/index.html))
- [ ] Add in ComponentSpeed parameter @reinhold-willcox 
- [ ] Add in MassTransferTrackerHistory values 8 and 9 #733 @reinhold-willcox 
- [ ] Clarify code defaults #582 
- [ ] Automatically import input and output parameter details from the compas source code

Low
- [ ] Better documentation of unintended consequences of CHE #346
- [ ] Add API for COMPAS src code, so developers can see what functions take which input/output. This is a little more involved but it you automatically set up an API reference for every single function in COMPAS (built using the docstring comments). 
- [ ] Add API for python post-processing functions, so users can make better use of them. [This page](https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/) explains it quite nicely for C++ code. [Example from LEGWORK](https://legwork.readthedocs.io/en/latest/modules.html)
- [ ] Copy code buttons: You can add “copy to clipboard” buttons to all of your code blocks super easily just by adding the sphinx_copybutton extension
- [ ] Inheritance chain: You could explain the inheritance chain stuff with the COMPAS functions [using this](https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html)
- [ ] Icons: Go into your conf.py and set html_favicon and html_logo to the COMPAS icon and logo respectively and it’ll update the icon in the browser tab and the logo in the top left of the docs respectively
